name: Build and Publish

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  ci:
    name: Build & Publish
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Identify version
        id: get-version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Project version: $VERSION"
      
      - name: Build 
        run: mvn -B -ntp -DskipTests=false clean package

      - name: Publish jars
        run: mvn -B deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${{ github.repository }} -Dmaven.deploy.skip=false -Dmaven.deploy.retryFailedDeploymentCount=0
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Github release
        uses: softprops/action-gh-release@v1
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get-version.outputs.version }}
          name: Release v${{ steps.get-version.outputs.version }}
          body: Release of version ${{ steps.get-version.outputs.version }}
          draft: false
          # A semver tag containing a '-' is a pre-release
          prerelease: ${{ contains(steps.get-version.outputs.version, '-') }}
          files: |
            target/remote-user-federation.jar
            target/remote-user-federation-jar-with-dependencies.jar
          generate_release_notes: false
        